call_center/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'', include('call_center_scheduler.urls', namespace="index")),
    url(r"^accounts/login/$", auth_views.login, name="login"),
    url(r"^accounts/logout/$", auth_views.logout, {"next_page": "/"}, name="logout"),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

call_center_scheduler/urls.py
from django.conf.urls import url

from call_center_scheduler.views import HomePageView, RequestSlotView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name="index"),
    url(r'^request_slot/$', RequestSlotView.as_view(), name="slotview")
]

call_center_scheduler/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Request(models.Model):
    project_name = models.CharField(max_length=100)
    number_of_slots = models.CharField(max_length=100)
    date_from = models.DateField(auto_now_add=True)
    date_to = models.DateField()
    email = models.EmailField()
    notes = models.TextField()
    approved = models.BooleanField(default=False)
    declined = models.BooleanField(default=False)


class Computer(models.Model):
    label = models.CharField(verbose_name="Label", max_length=100)
    serial_number = models.CharField(verbose_name="Serial Number", max_length=100)


class Booker(models.Model):
    computer_slot = models.ForeignKey(Computer, verbose_name="Computer Slot", related_name="call_center_computer")
    booker = models.ForeignKey(User, verbose_name="User Booking", related_name='inventory_borrower')
    date_booked = models.DateField(verbose_name="Date Booked", auto_now_add=True)
    date_released = models.DateField(verbose_name="Date Released", null=True)
    project = models.CharField(verbose_name="Project", max_length=100)

call_center_scheduler/views.py
from django.views.generic.edit import CreateView, FormView, UpdateView
from django.views.generic.base import TemplateView, TemplateResponseMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class DefaultMixin(LoginRequiredMixin, TemplateResponseMixin):
    pass


class HomePageView(DefaultMixin, TemplateView):
    template_name = "index.html"


class RequestSlotView(DefaultMixin, CreateView):
    template_name = "book.html"


class CreateComputerSlotView(DefaultMixin, CreateView):
    pass

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/favicon.ico">

    <title>Busara Center Call Center Schedule</title>

      <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- datepicker -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <script>
    $(function() {
      $( "#id_session_date" ).datepicker();
    });
    </script>
  </head>

  <body>

    {% block content%}

    {% endblock %}

</body>

templates/book.html
{% extends "base.html" %}
{% block content %}
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Busara Center Lab Schedule</a>
        </div>
        <nav class="collapse navbar-collapse" role="navigation">
          <ul class="nav navbar-nav">
              <li><a href="/request/">Book Session</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

                <li><a href="/accounts/login/"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Login</a></li>

          </ul>
        </nav>
      </div>
    </nav>
    <div class="container">
        <div class="container">
             <div class="content">
                <div class="col-md-6 col-md-offset-3">
                    <div class="panel panel-info">
                      <div class="panel-body">
                        <form role="form" action="" method="post" >
                            <input type='hidden' name='csrfmiddlewaretoken' value='uancGYQivda2ywDef1SH1y1mzfpDxcq2' />
                            <p>
                                <label for="name">Name:</label>
                                <input class="textinput form-control" id="id_name" maxlength="255" name="item_name" type="text" />
                            </p>
                            <p>
                                <label for="project">Project:</label>
                                <input class="textinput form-control" id="id_project" maxlength="255" name="number_of_items" type="text" />
                            </p>
                            <p>
                                <label for="id_your_email">No. of Slots:</label>
                                <input class="textinput form-control" id="id_your_email" maxlength="255" name="your_email" type="text" />
                            </p>
                            <p>
                                <label for="id_duration">Duration:</label>
                                <input class="textinput form-control" id="id_duration" maxlength="255" name="duration" type="text" />
                            </p>
                            <p>
                                <label for="id_project">Email Address:</label>
                                <input class="textinput form-control" id="id_project" maxlength="255" name="project" type="text" />
                            </p>
                            <p>
                                <label for="id_notes">Notes:</label>
                                <textarea class="textinput form-control" cols="40" id="id_notes" name="notes" rows="10"></textarea>
                            </p>
                            <input type="submit" name="submit" id="submit" value="Submit" class="btn btn-info pull-right">
                        </form>
                      </div>
                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Busara Center Call Center Schedule</a>
        </div>
        <nav class="collapse navbar-collapse" role="navigation">
          <ul class="nav navbar-nav">
              <li><a href="/request_slot/">Book Slot</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

                <li><a href="/accounts/login/"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> Login</a></li>

          </ul>
        </nav>
      </div>
    </nav>
    <div class="container" style="text-align: center">
         <div class="row">
             <div class="container">
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 1</h3>
                   <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                   <strong style="color:red;"><h4>In Use</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 2</h3>
                      <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                     <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                  </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 3</h3>
                     <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                     <strong style="color:red;"><h4>In Use</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 4</h3>
                    <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                    <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 5</h3>
                    <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                    <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 6</h3>
                     <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                     <strong style="color:red;"><h4>In Use</h4></strong>
                </div>
                  </div>
             </div>
         </div>
         <div class="row">
             <div class="container">
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 7</h3>
                   <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                  <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 8</h3>
                      <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                      <strong style="color:red;"><h4>In Use</h4></strong>
                  </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 9</h3>
                      <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                     <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 10</h3>
                     <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                     <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 11</h3>
                     <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                     <strong style="color:red;"><h4>In Use</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 12</h3>
                     <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                    <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                  </div>
             </div>
         </div>
         <div class="row">
             <div class="container">
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 13</h3>
                      <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                    <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 14</h3>
                      <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                     <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                  </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 15</h3>
                      <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                        <strong style="color:red;"><h4>In Use</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 16</h3>
                    <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                    <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 17</h3>
                       <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                      <strong style="color:green;"><h4 class="blinking">Available</h4></strong>
                 </div>
                 <div class="col-xs-12 col-sm-2">
                    <h3>Slot 18</h3>
                       <img src="{% static "comp.png"  %}" height="100%" width="80%" alt="My image"/>
                       <strong style="color:red;"><h4>In Use</h4></strong>
                  </div>
             </div>
         </div>
    </div>
{% endblock %}